# Generated by Django 2.2.12 on 2022-04-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='image',
        ),
    ]
