# Generated by Django 2.2.12 on 2022-04-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_userdata_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['username']},
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
    ]
